### ISSUE TITLE
Capture single window and audio

### ISSUE THREAD

**Issue by stuaxo** [kaihendry/recordmydesktop2.0#2]
Is it possible to capture a single window, along with any audio output that happens at the same time (not audio from the mic) ?

**Comment by kaihendry** [comment]
I think you should try https://github.com/lolilolicon/FFcast

You should control the recording audio from pavucontrol. :)

**Comment by stuaxo** [comment]
I did use it, I wasn't sure how to get it to capture audio from the loopback device, this seemed simpler :)   

I'll have another look though, I'm making something to start {someprogram} and loop audio at the same time.    

Since I want the audio to run at the same time for 10 - 30 second video there isn't time to use the gui to adjust the volume.

**Comment by stuaxo** [comment]
I've got this so far (based on various internet searches):

```
    CHUNK = 1024
    
    # Open Wave File and start play!
    rate, wave = wavread(sys.argv[1])
    wave = np.array(wave, dtype=np.float32)
    wave /= 2**15 # normalize -max_int16..max_int16 to -1..1

    block_length = 16

    stream = Stream()
    stream.start()
    pos=0
    while self.loop:
        data = wave[pos:pos+self.CHUNK*2]
        stream.write(data)
        pos += CHUNK*2
        if pos > len(wave):
            pos = 0
    stream.stop()
```

I don't get any buffer underruns, but there are a couple of things I think might be dodgy ... the CHUNK, and also - just looping straight back to zero ... fine on my own looping wav, but seems like this could do with either a circular buffer, or a wav where I add a small sample onto the end of the wave, that can be read on looping.

**Comment by stuaxo** [comment]
^ Deleted comment - wrong project :)
